version: 0.0
os: linux
files:
  - source: springboot-hello-world.jar
    destination: /home/ec2-user
  - source: StartServer.sh
    destination: /home/ec2-user

hooks:
  AfterInstall:
    - location: StartServer.sh
      timeout: 300
      runas: ec2-user
