version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # or corretto11 depending on your Java version
    commands:
      - echo "Installing dependencies..."
      - mvn install -DskipTests

  pre_build:
    commands:
      - echo "Running pre-build phase..."
      - mvn clean

  build:
    commands:
      - echo "Building the project..."
      - mvn package -DskipTests

  post_build:
    commands:
      - echo "Build completed successfully."
      - echo "You can add deployment steps here."

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
