version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven

  build:
    commands:
      - echo Building the project...
      - mvn clean package

artifacts:
  files:
    - target/*.jar
    - StartServer.sh   # Include your post-deploy script in the artifact
  discard-paths: yes                 # This ensures the artifact is zipped into a flat structure, not a folder structure

cache:
  paths:
    - '/root/.m2/**/*'               # Cache the Maven dependencies to speed up future builds
