version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven

  build:
    commands:
      - echo Building the project...
      - mvn clean package
      - cp target/*.jar springboot-hello-world.jar  # Ensure consistent filename

artifacts:
  files:
    - springboot-hello-world.jar
    - StartServer.sh
    - appspec.yml
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
